name: Gulp Task Runner
description: Run Gulp tasks from the command line to build assets
inputs:
  task:
    description: task to run
    required: true
runs:
  using: "composite"
  steps:

    - name: Dump github context
      run: echo "$GITHUB_CONTEXT"
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}

    - name: Dump env context
      run: echo "$ENV_CONTEXT"
      shell: bash
      env:
        ENV_CONTEXT: ${{ toJson(env) }}

    - run: git branch
      shell: bash

    - run: git branch --show-current
      shell: bash

    - name: Setup git config name
      id: git-config-user-name
      run: git config --global user.name github-actions
      shell: bash

    - name: Setup git config email
      id: git-config-user-email
      run: git config --global user.email github-actions@github.com
      shell: bash

    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install npm packages
      run: npm install --quiet
      shell: bash

    - name: Remove `package-lock.json` from repo
      run: rm package-lock.json
      shell: bash

    - name: Show files after `npm i`
      run: ls -la
      shell: bash

    - name: Run Gulp Task Runner for 'js'
      run: npx gulp js
      shell: bash

    - name: Remove `node_modules` when done
      run: rm -rf node_modules
      shell: bash

    - name: Show files after `gulp js`
      run: ls js -R
      shell: bash

    - name: Show commits if applicable
      run: git diff --compact-summary
      shell: bash

    - name: Add files
      run: git add -A
      shell: bash

    - name: Commit files
      run: git commit -m "build"
      shell: bash

    - name: Make sure there are not commits left
      run: git diff --compact-summary
      shell: bash

    - run: git branch
      shell: bash

    - run: git branch --show-current
      shell: bash

    - name: Push files
      run: git push
      shell: bash