name: Gulp Task Runner
description: Run Gulp tasks from the command line to build assets
inputs:
  task:
    description: task to run
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup git config name
      id: git-config-user-name
      if: ${{ env.GITHUB_NAME }}
      run: git config --global user.name ${{ env.GITHUB_NAME }}

    - name: Setup git config email
      id: git-config-user-email
      if: ${{ env.GITHUB_EMAIL }}
      run: git config --global user.email ${{ env.GITHUB_EMAIL }}

    - name: Dump github context
      run: echo "$GITHUB_CONTEXT"
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}

    - name: Dump env context
      run: echo "$ENV_CONTEXT"
      shell: bash
      env:
        ENV_CONTEXT: ${{ toJson(env) }}

    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Remove existing js/dist
      run: rm -rf js/dist

    - name: Show files after `rm -rf js/dist`
      run: ls -R

    - name: Install npm packages
      run: npm install --quiet

    - name: Remove `package-lock.json` from repo
      run: rm package-lock.json

    - name: Show files after `npm i`
      run: ls -la

    - name: Run Gulp Task Runner for 'js'
      run: npx gulp js

    - name: Show files after `gulp js`
      run: ls js -R

    - name: Show commits if applicable
      run: git diff

    - name: Commit files
      run: git commit -m "build"

    - name: Make sure no commits left
      run: git diff