name: Gulp Task Runner
description: Run Gulp tasks from the command line to build assets
inputs:
  task:
    description: task to run
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup git config name
      id: git-config-user-name
      run: git config --global user.name ${{ env.GITHUB_NAME || github-actions }}
      shell: bash

    - name: Setup git config email
      id: git-config-user-email
      if: ${{ env.GITHUB_EMAIL }}
      run: git config --global user.email ${{ env.GITHUB_EMAIL || github-actions@github.com }}
      shell: bash

    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install npm packages
      run: npm install --quiet
      shell: bash

    - name: Remove `package-lock.json` from repo
      run: rm package-lock.json
      shell: bash

    - name: Show files after `npm i`
      run: ls -la
      shell: bash

    - name: Run Gulp Task Runner for 'js'
      run: npx gulp js
      shell: bash

    - name: Show files after `gulp js`
      run: ls js -R
      shell: bash

    - name: Show commits if applicable
      run: git diff --compact-summary
      shell: bash

    - name: Commit files
      run: git commit -a -m "build"
      shell: bash

    - name: Make sure no commits left
      run: git diff --compact-summary
      shell: bash

    - name: Push files
      if: ${{ !env.ACT }}
      run: git push --tags
      shell: bash