name: Gulp Task Runner
description: Run Gulp tasks from the command line to build assets
inputs:
  task:
    description: task to run
    required: true
runs:
  using: "composite"
  steps:

    - name: Setup git config name
      id: git-config-user-name
      run: git config --global user.name github-actions
      shell: bash

    - name: Setup git config email
      id: git-config-user-email
      run: git config --global user.email <>
      shell: bash

    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install npm packages
      run: npm install --quiet
      shell: bash

    - name: Remove `package-lock.json` from repo
      run: rm package-lock.json
      shell: bash

    - name: Run Gulp Task Runner for 'js'
      run: npx gulp js
      shell: bash

    - name: Remove `node_modules` when done
      run: rm -rf node_modules
      shell: bash

    - name: Check if there are files to add
      run: git_add=$(git ls-files --others --exclude-standard)
      shell: bash

    - name: Add files
      if: ${#git_add} != 0
      run: git add -A
      shell: bash

    - name: Check if there are files to commit
      run: git_commit=$(git diff --compact-summary)
      shell: bash

    - name: Commit files
      if: ${#git_commit} != 0
      run: git commit -m "build"
      shell: bash

    - name: Push files
      if: ${#git_commit} != 0
      run: git push
      shell: bash