name: gulp-runner
run-name: Run Gulp

on: [ delete ]

jobs:

  gulpfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}

      - id: gulp-js
        uses: ./.github/actions/gulp
        with:
          task: js