name: gulp-runner
run-name: Run Gulp

on: [ push ]

jobs:

  gulpfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: gulp-js
        uses: ./.github/actions/gulp
        with:
          task: js