name: gulp-runner
run-name: Run Gulp

on:
  push:
    tags:
      - 'v*'

jobs:

  gulpfile:
    runs-on: ubuntu-latest
    steps:
      - id: gulp-js
        uses: ./.github/actions/gulp
        with:
          task: js