name: Setup PHP with Composer
on: [ push ]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
      - run: composer install