name: make-wordpress-plugin
run-name: Make WordPress Plugin

on:
  push:
    tags:
      - 'v*'
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Dump github context
        run: echo "$GITHUB_CONTEXT"
        shell: bash
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}

      - name: Setup PHP w/ Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Composer Install
        run: composer install

      - name: Clean up
        run: rm -rf .git .github .gitignore codeception.yml composer.lock css/src gulpfile.js js/src package.json tests

      - name: Zip Repo
        run: zip -r ${{ github.event.repository.name || 'plugin' }}.zip .

      - run: ls -la

      - name: Create Release w/ Asset
        id: create_release
        if: ${{ github.actor == github.repository_owner }}
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.run_number }}
          tag_name: ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
            - Third Change
          draft: false
          prerelease: false
          files: ./${{ github.event.repository.name || 'plugin'  }}.zip

      - name: Dump Release output
        if: ${{ github.actor == github.repository_owner }}
        run: echo "$RELEASE_OUTPUT"
        shell: bash
        env:
          RELEASE_OUTPUT: ${{ steps.create_release.outputs }}