name: Setup PHP with Composer
on:
  push:
    tags:
      - 'v*'
jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP w/ Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Composer Install
        run: composer install

      - name: Clean up
        run: rm -rf .git .github .gitignore codeception.yml composer.lock css/src gulpfile.js js/src package.json tests

      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.0
        with:
          type: 'zip'
          filename: 'plugin.zip'

      - name: Create Release w/ Asset
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.run_number }}
          tag_name: ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
            - Third Change
          draft: false
          prerelease: false
          files: ./plugin.zip