name: Setup PHP with Composer
on:
  push:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: ncipollo/release-action@v1
      - uses: actions/checkout@v3
        with:
          ref: plugin
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2
      - run: composer install