name: Setup PHP with Composer
on: [ push ]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup PHP w/ Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: Clean up
        run: rm -rf .git .github .gitignore codeception.yml css/src gulpfile.js js/src package.json tests vendor

      - name: Composer Install
        run: composer install

      - name: Save Artifact
        uses: actions/upload-artifact@v3
        with:
          name: plugin
          path: .