name: sync-versions
run-name: Sync Versions

on:
  workflow_dispatch:

jobs:

  main:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Versions
        id: sync-versions
        uses: ./.github/actions/sync-versions